(component
	(type $host (instance
		(type $wait (func async (result u32)))
		(export "wait" (func (type $wait)))
	))
	(import "test:host/root" (instance $host (type $host)))
	(alias export $host "wait" (func $wait))
	(core module $memory (memory (export "memory") 1))
	(core instance $memory (instantiate $memory))
	(core func $lowered-wait (canon lower (func $wait) async (memory $memory "memory")))
	(core func $waitable-set-new (canon waitable-set.new))
	(core func $waitable-join (canon waitable.join))
	(core func $task-return (canon task.return (result u32)))
	(core func $task-cancel (canon task.cancel))
	(core module $implementation
		(import "" "memory" (memory 1))
		(import "" "wait" (func $wait (param i32) (result i32)))
		(import "" "waitable-set-new" (func $waitable-set-new (result i32)))
		(import "" "waitable-join" (func $waitable-join (param i32 i32)))
		(import "" "task-return" (func $task-return (param i32)))
		(import "" "task-cancel" (func $task-cancel))
		(func (export "get-value") (result i32)
			(local $status i32) (local $waitable-set i32)
			(local.set $status (call $wait (i32.const 0)))
			(if (i32.ne (i32.and (local.get $status) (i32.const 15)) (i32.const 1))
				(then unreachable))
			(local.set $waitable-set (call $waitable-set-new))
			(call $waitable-join
				(i32.shr_u (local.get $status) (i32.const 4))
				(local.get $waitable-set))
			(i32.or (i32.const 2) (i32.shl (local.get $waitable-set) (i32.const 4)))
		)
		(func (export "callback") (param i32 i32 i32) (result i32)
			(if (i32.eq (local.get 0) (i32.const 6))
				(then (call $task-cancel))
				(else (call $task-return (i32.const 42)))
			)
			i32.const 0
		)
	)
	(core instance $implementation-instance (instantiate $implementation
		(with "" (instance
			(export "memory" (memory $memory "memory"))
			(export "wait" (func $lowered-wait))
			(export "waitable-set-new" (func $waitable-set-new))
			(export "waitable-join" (func $waitable-join))
			(export "task-return" (func $task-return))
			(export "task-cancel" (func $task-cancel))
		))
	))
	(alias core export $implementation-instance "get-value" (core func $get-value))
	(alias core export $implementation-instance "callback" (core func $callback))
	(func $lifted-get-value async (result u32) (canon lift
		(core func $get-value)
		async
		(memory $memory "memory")
		(callback (func $callback))
	))
	(instance $root (export "get-value" (func $lifted-get-value)))
	(export "test:plugin/root" (instance $root))
)
